### ISSUE TITLE
Highlight the connection name

### ISSUE THREAD

**Issue by severindellsperger** [wemulate/wemulate-frontend#22]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
At the moment, the connection name is unremarkable. Still, it is an important field thus I would like to highlight it with e.g. a larger font size.

**Describe alternatives you've considered**
Maybe highlight it in bold or some other style.

**Additional context**

**Comment by DNS320** [comment]
Was changed with release: https://github.com/wemulate/wemulate-frontend/releases/tag/v2.0.3
(no merge request, shame on me)
