### ISSUE TITLE
Input validation Error on Enter

### ISSUE THREAD

**Issue by priisig** [wemulate/wemulate-frontend#6]
**Describe the bug**
When i put a number in packet loss field and press enter, the validator tells its invalid.
But i can apply it with the save button without any problem.

**To Reproduce**
1. Enter 0.1 into packetloss field
2. Press Enter

**Expected behavior**
No validation Error

**Screenshots**
![image](https://user-images.githubusercontent.com/28090657/145551539-c387a404-601d-43ef-91bb-f5f7d2ce8bd2.png)

**Comment by DNS320** [comment]
Thank you for reporting. We will try to fix this soon.

**Comment by DNS320** [comment]
This issue was solved with #7.
The unwanted browser validation was removed by using HTML input fields with _type=text_ instead of _type=number_.
